const app = document.querySelector('#app');
const steps = ['DETAILS', 'PERMISSION', 'REVIEW', 'DONE'];
const permissionLabels = { EARLY_ARRIVAL: 'Early Arrival', LATE_DEPARTURE: 'Late Departure', BOTH: 'Both' };
const permissionDescriptions = { EARLY_ARRIVAL: 'I want to come to college early for practice.', LATE_DEPARTURE: 'I want to stay in college late for practice.', BOTH: 'I want permission for both early arrival and late departure.' };
const GOOGLE_APPS_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbzZdVX9d02EePWFmucUAN_BU93EJGA0uSNJfASplDhrLL_vIcHkKNdKdmWsPyTgNURGDg/exec';
let currentStep = 0;
let isSubmitting = false;
let form = { fullName: '', mobile: '', enrollment: '', year: '', permission: '', confirmed: false };
let errors = {};

function render() {
  if (currentStep === 0) return renderLanding();
  if (currentStep === 1) return renderDetails();
  if (currentStep === 2) return renderPermission();
  if (currentStep === 3) return renderReview();
  return renderSuccess();
}
function topbar() { return `<header class="topbar"><a class="brand" href="#" onclick="goHome(event)"><span class="brand-mark">S</span><span><strong class="brand-name">SANGATHAN</strong><small class="brand-sub">Amity University Rajasthan</small></span></a>${currentStep > 0 && currentStep < 4 ? `<span class="eyebrow">Day Scholar Portal</span>` : ''}</header>`; }
function renderLanding() { app.innerHTML = `${topbar()}<section class="landing"><div class="landing-copy"><span class="eyebrow">Sports event · 2026</span><h1>Train together.<span>Compete together.</span></h1><p class="lede">Request permission to arrive early or stay late for SANGATHAN practice.</p><button class="primary-button" onclick="startRequest()">Start request <span class="arrow">↗</span></button></div><div class="event-stamp"><span class="stamp-detail top">Day scholars only</span><div class="stamp-ring"><div class="stamp-core"><strong>SG</strong><span>Move as one</span></div></div><span class="stamp-detail bottom">AUR · Jaipur</span></div></section><p class="footer-note">Official practice permission portal</p>`; }
function progress() { return `<div class="progress" aria-label="Step ${currentStep} of 4">${steps.map((step, index) => `<span class="progress-bar ${index <= currentStep - 1 ? 'active' : ''}" title="${step}"></span>`).join('')}</div>`; }
function formShell(step, title, content) { return `${topbar()}<section class="form-page"><div class="form-header"><div><span class="eyebrow">0${step} — ${steps[step - 1]}</span><h1>${title}</h1></div><span class="step-count">0${step} / 04</span></div>${progress()}${content}</section>`; }
function field(name, label, type, placeholder, value, extra = '') { return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" placeholder="${placeholder}" value="${escapeHtml(value)}" ${extra} oninput="updateField('${name}', this.value)" /><span class="field-error">${errors[name] || ''}</span></div>`; }
function renderDetails() { const content = `<div class="form-section">${field('fullName','Full name','text','Enter your full name',form.fullName,'autocomplete="name"')} ${field('mobile','Mobile number','tel','10-digit mobile number',form.mobile,'inputmode="numeric" maxlength="10" autocomplete="tel"')} ${field('enrollment','Enrollment number','text','Enter your enrollment number',form.enrollment,'autocomplete="off"')}<div class="field"><label for="year">Year</label><select id="year" onchange="updateField('year', this.value)"><option value="">Select your year</option>${['1st Year','2nd Year','3rd Year','4th Year'].map(year => `<option ${form.year === year ? 'selected' : ''}>${year}</option>`).join('')}</select><span class="field-error">${errors.year || ''}</span></div></div><div class="form-actions"><button class="back-button" onclick="goHome()">Cancel</button><button class="primary-button" onclick="continueDetails()">Continue <span class="arrow">→</span></button></div>`; app.innerHTML = formShell(1, 'Student details', content); }
function renderPermission() { const options = [['EARLY_ARRIVAL','🌅'],['LATE_DEPARTURE','🌙'],['BOTH','↔']]; const cards = options.map(([key, icon]) => `<button class="permission-card ${form.permission === key ? 'selected' : ''}" onclick="selectPermission('${key}')"><span class="permission-icon">${icon}</span><span><h3>${permissionLabels[key]}</h3><p>${permissionDescriptions[key]}</p></span><span class="radio"></span></button>`).join(''); const content = `<div class="form-section"><div><p class="lede" style="font-size:15px;margin-bottom:18px">What permission do you require?</p><div class="permission-grid">${cards}</div><div class="field-error" style="margin-top:12px">${errors.permission || ''}</div></div></div><div class="form-actions"><button class="back-button" onclick="previousStep()">← Back</button><button class="primary-button" onclick="continuePermission()">Review request <span class="arrow">→</span></button></div>`; app.innerHTML = formShell(2, 'Permission required', content); }
function renderReview() { const content = `<div class="form-section"><div class="review-card"><div class="review-row"><span class="review-label">Name</span><strong class="review-value">${escapeHtml(form.fullName)}</strong></div><div class="review-row"><span class="review-label">Mobile number</span><strong class="review-value">${maskMobile(form.mobile)}</strong></div><div class="review-row"><span class="review-label">Enrollment number</span><strong class="review-value">${escapeHtml(form.enrollment)}</strong></div><div class="review-row"><span class="review-label">Year</span><strong class="review-value">${escapeHtml(form.year)}</strong></div><div class="review-row"><span class="review-label">Permission</span><strong class="review-value">${permissionLabels[form.permission]}</strong></div></div><button class="edit-button" onclick="editDetails()">Edit details</button><label class="confirm"><input type="checkbox" ${form.confirmed ? 'checked' : ''} onchange="setConfirmed(this.checked)" /> <span>I confirm that the information provided by me is correct and this request is related to SANGATHAN practice.</span></label>${errors.confirmed ? `<div class="alert">${errors.confirmed}</div>` : ''}</div><div class="form-actions"><button class="back-button" onclick="previousStep()">← Back</button><button class="primary-button" ${isSubmitting ? 'disabled' : ''} onclick="submitRequest()">${isSubmitting ? '<span class="spinner"></span> Submitting...' : 'Submit request'} <span class="arrow">↗</span></button></div>`; app.innerHTML = formShell(3, 'Review request', content); }
function renderSuccess() { const saved = JSON.parse(localStorage.getItem('sangathan_last_request') || '{}'); app.innerHTML = `${topbar()}<section class="success-page"><div class="success-wrap"><div class="checkmark">✓</div><span class="eyebrow">04 — DONE</span><h1>Request submitted</h1><p>Your Day Scholar practice permission request has been recorded successfully.</p><div class="request-id"><span>Request ID</span><strong>${saved.requestId || 'SNG-PR-XXXXX'}</strong></div><div class="contact"><h3>Having a problem?</h3><p>If you face any problem regarding this form or your practice permission request, please contact:<br><strong>Shivam Bindal</strong><br>Student &amp; Registration Coordinator<br><a href="tel:7073415826">7073415826</a></p></div></div></section>`; }
function updateField(name, value) { form[name] = value; if (errors[name]) { delete errors[name]; const error = document.querySelector(`#${name}`)?.parentElement.querySelector('.field-error'); if (error) error.textContent = ''; } }
function startRequest() { currentStep = 1; render(); }
function goHome(event) { if (event) event.preventDefault(); currentStep = 0; errors = {}; render(); }
function previousStep() { errors = {}; currentStep = Math.max(1, currentStep - 1); render(); }
function continueDetails() { errors = {}; if (!form.fullName.trim()) errors.fullName = 'Please enter your full name.'; if (!/^[6-9]\d{9}$/.test(form.mobile)) errors.mobile = 'Please enter a valid mobile number.'; if (!form.enrollment.trim()) errors.enrollment = 'Please enter your enrollment number.'; if (!form.year) errors.year = 'Please select your year.'; if (Object.keys(errors).length) return render(); currentStep = 2; render(); }
function selectPermission(permission) { form.permission = permission; errors.permission = ''; render(); }
function continuePermission() { if (!form.permission) { errors.permission = 'Please select the permission you require.'; render(); return; } currentStep = 3; render(); }
function setConfirmed(value) { form.confirmed = value; errors.confirmed = ''; }
function editDetails() { currentStep = 1; render(); }
async function submitRequest() { if (!form.confirmed) { errors.confirmed = 'Please confirm that the information provided is correct.'; render(); return; } isSubmitting = true; render(); try { const result = GOOGLE_APPS_SCRIPT_URL ? await submitToGoogleSheet() : await submitToLocalDemo(); if (!result.ok) { errors.confirmed = result.requestId ? `${result.message} Request ID: ${result.requestId}` : result.message; isSubmitting = false; render(); return; } localStorage.setItem('sangathan_last_request', JSON.stringify({ ...form, requestId: result.requestId, submittedAt: result.submittedAt })); currentStep = 4; isSubmitting = false; render(); } catch (error) { errors.confirmed = 'Unable to connect. Please check your internet connection and try again.'; isSubmitting = false; render(); } }
async function submitToGoogleSheet() { const response = await fetch(GOOGLE_APPS_SCRIPT_URL, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify({ fullName: form.fullName, mobileNumber: form.mobile, enrollmentNumber: form.enrollment, year: form.year, permissionType: form.permission }) }); return response.json(); }
async function submitToLocalDemo() { const duplicateKey = `${form.enrollment.trim().toLowerCase()}|${form.mobile}`; const existing = JSON.parse(localStorage.getItem('sangathan_submissions') || '{}'); if (existing[duplicateKey]) return { ok: false, message: 'A request has already been submitted using these details.', requestId: existing[duplicateKey] }; await new Promise(resolve => setTimeout(resolve, 750)); const requestId = `SNG-PR-${Math.random().toString(36).slice(2,8).toUpperCase()}`; existing[duplicateKey] = requestId; localStorage.setItem('sangathan_submissions', JSON.stringify(existing)); return { ok: true, requestId, submittedAt: new Date().toISOString() }; }
function maskMobile(value) { return value.length === 10 ? `${value.slice(0,2)}••••••${value.slice(-2)}` : value; }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char])); }
render();
